import random

global endGame
endGame = True


# ** MAIN FUNCTIONALITY OF THE GAME **
def game():
    print("\n~~Enter a range of numbers~~")

    # Setting global variables for the lower and upper range numbers
    global lowerBound
    global upperBound

    # Ensures that the user's input is valid
    while True:
        try:
            # Allowing user to select the lower bound of range
            lowerBound = int(input("Enter the lower bound number: "))
            break
        except ValueError:
            print("You can only input integers. Try again.\n")

    while True:
        try:
            # Allowing user to select the upper bound of range
            upperBound = int(input("Enter the upper bound number: "))

            # Checking if the number entered is greater than the lower bound number
            while upperBound < lowerBound:
                print("\nUpper bound number must be greater or equal to the lower bound number. Try again.")
                upperBound = int(input("Enter the upper bound number: "))

            break
        except ValueError:
            print("You can only input integers. Try again.\n")

    # Generating a random number between the user range
    randomNumber = random.randint(lowerBound, upperBound)

    # Setting a global variable to keep track of lives remaining
    global lives
    lives = 3
    userInput = 0
    while lives != 0:
        # Allows the user to input a guess
        userInput = int(input("\nEnter your guess: "))

        # Checking if the number inputted is in valid range
        if lowerBound <= userInput <= upperBound:
            # If number matches to that of the random number
            if userInput < randomNumber:
                print("The secret number is greater.")

            if userInput > randomNumber:
                print("The secret number is smaller.")

            if randomNumber == userInput:
                print("You Win! :)")
                break
            else:
                lives -= 1
                print("Incorrect! Lives remaining: " + str(lives))
        else:
            print("Input a number in range of: " + str(lowerBound) + "-" + str(upperBound))

    if lives == 0:
        print("\nYou Lose! :(")
        print("The number was: " + str(randomNumber))


# ** Main program starts here **

# User's name
name = ""
# Taking input of the user
name = str(input("Enter your name: " + name))

# Greeting the user
print("\nHello " + name + "!")

print("\n*********************************")
print("* Welcome to Guess that Number! *")
print("*********************************\n")

print("********************************************************************")
print("* The purpose of this game is to allow a user to guess the number  *")
print("* generated by the computer based on a range selected by the user. *")
print("*             The player has a total of three lives.               *")
print("********************************************************************\n")

game()

while endGame:
    playAgain = str(input("\nDo you want to play again? "))
    if playAgain.lower() == "yes":
        game()
    elif playAgain.lower() == "no":
        endGame = False
        print("\nThank you for playing " + name + "! ^o^")
